### ISSUE TITLE
Explanation of the timestamps in the Destlist

### ISSUE THREAD

**Issue by randomaccess3** [woanware/JumpLister#4]
Is there any explanation as to where you obtain the Timestamp (New) and Timestamp (Birth) from?

I've got a jumplist where the date/time and the timestamp columns dont match and I can't seem to find any literature explaining where you got the Timestamp column.

**Comment by woanware** [comment]
Jumplist entries are basically LNK files, and LNK files have two GUID/UUID's associated with them. The GUID/UUID's are made up from the MAC address of the host and a timestamp. Look at HarryP's paper starting on page 12:

http://computerforensics.parsonage.co.uk/downloads/TheMeaningofLIFE.pdf
